const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Turret,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Behaviors.Turret.Acts.SetEnabled,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Behaviors.LOS.Acts.AddObstacle,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Cnds.OnArrived,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.EightDir.Acts.SetVectorX,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.EightDir.Acts.SetVectorY
	];
};
self.C3_JsPropNameTable = [
	{Твердый: 0},
	{Барьер: 0},
	{Поле: 0},
	{"8направлении": 0},
	{Прокрутитьдо: 0},
	{Разрушитель: 0},
	{Прикрепить: 0},
	{Турель: 0},
	{БашняР: 0},
	{Синусоида: 0},
	{Ловушка: 0},
	{Угасание: 0},
	{Трейсер: 0},
	{Мышь: 0},
	{Пуля: 0},
	{Снаряд: 0},
	{ВзрывСнаряд: 0},
	{Выстрел: 0},
	{Портал: 0},
	{Телепортация: 0},
	{Поискпути: 0},
	{Танк: 0},
	{Полезрения: 0},
	{Пушка: 0},
	{ВзрывТанка: 0},
	{Огонь: 0},
	{Счетчик: 0},
	{GAMEOVER: 0},
	{КнопкаВыстрел: 0},
	{Управление: 0},
	{Центр: 0},
	{Тач: 0},
	{Клавиатура: 0},
	{Аудио: 0},
	{Счет: 0},
	{Перезарядка: 0}
];

self.InstanceType = {
	Барьер: class extends self.ITiledBackgroundInstance {},
	Поле: class extends self.ITiledBackgroundInstance {},
	Разрушитель: class extends self.ISpriteInstance {},
	БашняР: class extends self.ISpriteInstance {},
	Ловушка: class extends self.ISpriteInstance {},
	Трейсер: class extends self.ISpriteInstance {},
	Мышь: class extends self.IInstance {},
	Снаряд: class extends self.ISpriteInstance {},
	ВзрывСнаряд: class extends self.ISpriteInstance {},
	Выстрел: class extends self.ISpriteInstance {},
	Портал: class extends self.ISpriteInstance {},
	Телепортация: class extends self.ISpriteInstance {},
	Танк: class extends self.ISpriteInstance {},
	Пушка: class extends self.ISpriteInstance {},
	ВзрывТанка: class extends self.ISpriteInstance {},
	Огонь: class extends self.ISpriteInstance {},
	Счетчик: class extends self.ISpriteFontInstance {},
	GAMEOVER: class extends self.ISpriteFontInstance {},
	КнопкаВыстрел: class extends self.ISpriteInstance {},
	Управление: class extends self.ISpriteInstance {},
	Центр: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Клавиатура: class extends self.IInstance {},
	Аудио: class extends self.IInstance {}
}